update views and urls config
gcivil-nyu-org/team-4-inperson pull request #90
Opened 2022-10-10 22:32 UTC by N17270182

2022-10-10 23:57 UTC, ncolosso requested changes
Have some comments before we can merge this PR

- We have config for the Courses and Professors apps in the Search app here, we'll want to put the right configurations in the right apps (i.e., Courses in Courses, Professors in Professors, etc).
- `urls.py` - the URL/name choice here could be revised. For Course ID, we'll be brought to the Course Detail page, so maybe we change the name to `course-detail`. For the URL, do we really need `ratenyu.com/{course_id}/course_result_by_id`? I think just `ratenyu.com/{course_id}` could work.
- `views.py` - We need to use render() functionality here since we are passing data and templtes, HttpResponse won't cut it. The Django tutorial we did for the personal assignment would be a good reference for using render() with context data.

2022-10-11 00:28 UTC, N17270182 commented
Good catch on the course_id part, it should go straight to the course detail page. I'll change the url to ratenyu.com/{course_id} and name to course-detail.(later maybe)

The second argument of render() needs a template name, but since you said you are going to create the template, so I just use the HttpResponse for now, and will change to render() later.

2022-10-11 15:19 UTC, ncolosso approved these changes

2022-10-11 15:22 UTC, ujjwalvkulkarni approved these changes

2022-10-11 15:23 UTC, merged