Created models for professor and course
gcivil-nyu-org/team-4-inperson pull request #97
Opened 2022-10-14 16:02 UTC by ujjwalvkulkarni

2022-10-14 16:25 UTC, N17270182 approved these changes

2022-10-14 17:15 UTC, ncolosso commented
> 

agree with viren

2022-10-14 17:26 UTC, ncolosso requested changes
Please add .DS_store to .gitignore and remove it from this PR

2022-10-17 19:53 UTC, ncolosso approved these changes

2022-10-17 23:22 UTC, merged